[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pre_sale_contract = "4zN5GLABGR1zqjSfpWmcdRAvLr5YnLUWxfcfAvDguBS9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
